#!/usr/bin/env bash
set -e
# don't change these 4 lines
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TRAINING=$1;
INPUT=$2;
OUTPUT=$3;
# prepare the training data
python $SCRIPTDIR/preprocess.py $TRAINING | python $SCRIPTDIR/unknown.py > $SCRIPTDIR/train.trees.pre.unk
# run your parser on the passed-in input
python $SCRIPTDIR/q1.py $INPUT > $SCRIPTDIR/dev.parses
# do final transformation of the parsed data so it is compatible with the true trees.
# this will write to the specified output  
python $SCRIPTDIR/postprocess.py $SCRIPTDIR/dev.parses > $OUTPUT



